build: false

environment:
    PYTHON: "C:\\Python38-x64"

    CONAN_USERNAME: "ltjax"
    CONAN_LOGIN_USERNAME: "ltjax"
    CONAN_CHANNEL: "testing"
    CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
    CONAN_UPLOAD: "https://api.bintray.com/conan/ltjax/conan"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: macos
          CONAN_APPLE_CLANG_VERSIONS: "11.0"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  # Windows build
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan --upgrade
  - cmd: pip.exe install conan_package_tools
  - cmd: conan user # It creates the conan data directory
  # macOS build
  - sh: chmod +x .appveyor/install.sh
  - sh: .appveyor/install.sh

test_script:
  # Windows build
  - cmd: python build.py
  # macOS build
  - sh: chmod +x .appveyor/run.sh
  - sh: .appveyor/run.sh
